server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    config:
      enabled: false
      import-check:
        enabled: false

    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - PreserveHostHeader

      routes:
        - id: ecofy-auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: ecofy-ingestion
          uri: http://localhost:8082
          predicates:
            - Path=/ingestion/**

        - id: ecofy-categorization
          uri: http://localhost:8083
          predicates:
            - Path=/categorization/**

        - id: ecofy-budgeting
          uri: http://localhost:8084
          predicates:
            - Path=/budgeting/**

        - id: ecofy-insights
          uri: http://localhost:8085
          predicates:
            - Path=/insights/**

        - id: ecofy-notification
          uri: http://localhost:8086
          predicates:
            - Path=/notification/**

        - id: ecofy-users
          uri: http://localhost:8087
          predicates:
            - Path=/users/**

# Logging de access (Kafka opcional)
ecofy:
  gateway:
    logging:
      enabled: true
      topic-name: gateway.access.log
      kafka:
        enabled: false  # mude para true quando quiser publicar no Kafka

# Config Kafka (somente necessário se ecofy.gateway.logging.kafka.enabled=true)
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
