services:
  api-gateway:
    build:
      context: ../../api-gateway
    container_name: ecofy-api-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # possivel ysar logging pro kafka no gateway
      ECOFY_GATEWAY_LOGGING_KAFKA_ENABLED: "false"
      ECOFY_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks: [ecofy-net]

  ms-auth:
    build:
      context: ../../ms-auth
    container_name: ecofy-ms-auth
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-auth:5432/ecofy_auth
      DB_USER: ecofy_auth
      DB_PASS: ecofy_auth
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # Maildev (infra)
      MAIL_HOST: maildev
      MAIL_PORT: "1025"

      # issuer coerente com gateway
      JWT_ISSUER: http://api-gateway:8080/auth
    depends_on:
      postgres-auth:
        condition: service_healthy
      kafka:
        condition: service_healthy
      maildev:
        condition: service_started
    networks: [ecofy-net]

  ms-ingestion:
    build:
      context: ../../ms-ingestion
    container_name: ecofy-ms-ingestion
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-ingestion:5432/ecofy_ingestion
      DB_USER: ecofy_ingestion
      DB_PASS: ecofy_ingestion
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json
    depends_on:
      postgres-ingestion:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

  ms-categorization:
    build:
      context: ../../ms-categorization
    container_name: ecofy-ms-categorization
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-categorization:5432/ecofy_categorization
      DB_USER: ecofy_categorization
      DB_PASS: ecofy_categorization
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json
    depends_on:
      postgres-categorization:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

  ms-budgeting:
    build:
      context: ../../ms-budgeting
    container_name: ecofy-ms-budgeting
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-budgeting:5432/ecofy_budgeting
      DB_USER: ecofy_budgeting
      DB_PASS: ecofy_budgeting
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json
    depends_on:
      postgres-budgeting:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

  ms-insights:
    build:
      context: ../../ms-insights
    container_name: ecofy-ms-insights
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-insights:5432/ecofy_insights
      DB_USER: ecofy_insights
      DB_PASS: ecofy_insights
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json

      INS_CLIENT_CATEGORIZATION_BASE_URL: http://ms-categorization:8083/categorization
      INS_CLIENT_BUDGETING_BASE_URL: http://ms-budgeting:8084/budgeting
    depends_on:
      postgres-insights:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

  ms-notification:
    build:
      context: ../../ms-notification
    container_name: ecofy-ms-notification
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      MONGO_URI: mongodb://mongo-notification:27017/ecofy_notification
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json
      # client ms-users
      NTF_USER_PROFILE_BASE_URL: http://ms-users:8087/users
    depends_on:
      mongo-notification:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

  ms-users:
    build:
      context: ../../ms-users
    container_name: ecofy-ms-users
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://postgres-users:5432/ecofy_users
      DB_USER: ecofy_users
      DB_PASS: ecofy_users
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_JWKS_URI: http://ms-auth:8081/auth/.well-known/jwks.json
      AUTH_MS_BASE_URL: http://ms-auth:8081/auth
    depends_on:
      postgres-users:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ms-auth:
        condition: service_started
    networks: [ecofy-net]

networks:
  ecofy-net:
    external: true
