services:

  # Kafka (único)
  kafka:
    image: apache/kafka:4.1.1
    container_name: ecofy-kafka
    restart: unless-stopped
    ports:
      - "9092:9092"      # opcional manter, mas recomendo usar 19092 como externo
      - "19092:19092"    # externo (host)
      - "9093:9093"      # controller
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:19092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 168
    volumes:
      - ecofy-kafka-data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "bash -lc 'unset JMX_PORT; /opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 >/dev/null 2>&1'" ]
      interval: 15s
      timeout: 10s
      retries: 10
    networks: [ ecofy-net ]

  kafka-init:
    image: apache/kafka:4.1.1
    container_name: ecofy-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      TOPICS_FILE: "/scripts/../topics.yml"
    volumes:
      - ../kafka/scripts:/scripts:ro
      - ../kafka/topics.yml:/topics.yml:ro
    entrypoint: [ "bash", "-lc", "/scripts/create-topics.sh" ]
    networks: [ ecofy-net ]
    restart: "no"

  # Postgres (ms-insights)
  postgres-insights:
    image: postgres:16-alpine
    container_name: ecofy-postgres-insights
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecofy_insights
      POSTGRES_USER: ecofy_insights
      POSTGRES_PASSWORD: ecofy_insights
      TZ: UTC
    ports:
      - "5437:5432"
    volumes:
      - ecofy-insights-db-data:/var/lib/postgresql/data
      # opcional (se você tiver scripts de init)
      # - ../postgres/init/insights:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecofy_insights -d ecofy_insights"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: [ ecofy-net ]


volumes:
  ecofy-insights-db-data:
  ecofy-kafka-data:

networks:
  ecofy-net:
    name: ecofy-net
